---
# tasks file for nxrm3-list-objects

- name: Calling NXRM3 API 
  uri:
    url: "{{ nxrm3_item.host }}:{{ nxrm3_item.port }}/{{ nxrm3_api }}"
    user: "{{ nxrm3_item.user }}"
    password: "{{ nxrm3_item.passwd }}"
    headers:
      Content-Type: "application/json"
    method: GET
    status_code: 200,204
    force_basic_auth: yes
  loop: "{{ nxrm3_instances }}"
  loop_control:
     loop_var: nxrm3_item
  register: op

- debug:
    var: op

