- hosts: nxrm3_controller
  vars:
    security_type: privilege-repository
  roles:
    - { role: nxrm3-list-objects, nxrm3_security_type: "{{ security_type }}", nxrm3_api: "{{ nxrm3_privilege_repository_api }}" }
    
